[workspace]

members = [
    "bem",
    "element",
    "fmm",
    "grid",
    "hyksort",
    "quadrature",
    "tools",
    "tree",
    "kernel",
    "traits",
]

default-members = [
    "bem",
    "element",
    "fmm",
    "grid",
    "hyksort",
    "quadrature",
    "tools",
    "tree",
    "kernel",
    "traits",
]
