[workspace]

members = [
    "element",
    "quadrature",
    "tools",
    "tree",
    "hyksort",
    "fmm",
    "traits"
]

default-members = [
    "element",
    "quadrature",
    "tools",
    "tree",
    "fmm",
    "traits"
]