[features]
# Treat warnings as a build error.
strict = []

[package]
name = "bempp-fmm"
version = "0.1.0"
edition = "2021"
authors = ["Srinath Kailasa <srinathkailasa@gmail.com>"]
description = "FMM in Rust"
license = "BSD-3-Clause"
homepage = "https://github.com/bempp/bempp-rs"
repository = "https://github.com/bempp/bempp-rs"
readme = "README.md"
keywords = ["numerics"]
categories = ["mathematics", "science"]

[lib]
name = "bempp_fmm"
crate-type = ["lib", "cdylib"]

[dependencies]
bempp-tools = { path = "../tools" }
bempp-tree = { path = "../tree" }
bempp-traits = { path = "../traits" }
approx = "0.5"
cauchy = "0.4.*"
itertools = "0.10"
mpi = { version = "0.6.*" }
rand = "0.8.*"
ndarray = { version = "*", features = ["blas"]}
blas-src = { version = "*", features = ["openblas"] }
openblas-src = { version = "*", features = ["cblas", "system"] }
ndarray-linalg = { version = "*", features = ["openblas-system"] }
float-cmp = "0.9.0"
rayon = "1.5.1"
num_cpus = "1.0"
