#![cfg_attr(nightly, feature(core_intrinsics))]

use bempp_generation::generate_kernels;
use bempp_traits::element::FiniteElement;

fn main() {
    generate_kernels!(
        dp0_dp0_kernel,
        "Lagrange",
        "Triangle",
        0,
        true,
        "Lagrange",
        "Triangle",
        0,
        true,
        "Lagrange",
        "Triangle",
        1,
        false,
        "Lagrange",
        "Triangle",
        1,
        false
    );
    generate_kernels!(
        p1_p1_kernel,
        "Lagrange",
        "Triangle",
        1,
        false,
        "Lagrange",
        "Triangle",
        1,
        false,
        "Lagrange",
        "Triangle",
        1,
        false,
        "Lagrange",
        "Triangle",
        1,
        false
    );
    generate_kernels!(
        p1_p2_kernel,
        "Lagrange",
        "Triangle",
        1,
        false,
        "Lagrange",
        "Triangle",
        2,
        false,
        "Lagrange",
        "Triangle",
        1,
        false,
        "Lagrange",
        "Triangle",
        1,
        false
    );

    generate_kernels!(
        high_order_geometry_kernel,
        "Lagrange",
        "Triangle",
        1,
        false,
        "Lagrange",
        "Triangle",
        1,
        false,
        "Lagrange",
        "Triangle",
        2,
        false,
        "Lagrange",
        "Triangle",
        2,
        false
    );

    generate_kernels!(
        mixed_order_geometry_kernel,
        "Lagrange",
        "Triangle",
        1,
        false,
        "Lagrange",
        "Triangle",
        1,
        false,
        "Lagrange",
        "Triangle",
        2,
        false,
        "Lagrange",
        "Triangle",
        1,
        false
    );
}
