name: 🧪📅

on:
  schedule:
    - cron: "0 7 * * 1"

jobs:
  run-tests-rust:
    name: Run Rust tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: ["stable", "beta", "nightly"]
        mpi: [ 'mpich', 'openmpi']
    steps:
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          components: rustfmt
      - name: Set up MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}
      - name: Install cargo-mpirun
        run: cargo install cargo-mpirun
      - uses: actions/checkout@v3
      - name: Install LAPACK, OpenBLAS
        run:
          sudo apt-get install -y libopenblas-dev liblapack-dev

      - name: Build rust library
        run: cargo build --features "strict"
      - name: Build rust library in release mode
        run: cargo build --release --features "strict"
      - name: Build rust library in release mode with mpi
        run: cargo build --release --features "strict,mpi"


      - name: Run unit tests
        run: cargo test --features "strict"
      - name: Run unit tests in release mode
        run: cargo test --release --features "strict"
      - name: Run unit tests with mpi enabled
        run: cargo test --features "mpi,strict"
      - name: Run unit tests in release mode with mpi enabled
        run: cargo test --release --features "mpi,strict"
      - name: Run tests
        run: cargo test --examples --release --features "mpi,strict"
      - name: Test benchmarks build
        run: cargo bench --no-run --features "mpi,strict"
      - name: Run examples
        run: |
          python3 find_examples.py
          chmod +x examples.sh
          ./examples.sh

      - name: Build docs
        run: cargo doc --features "mpi,strict" --no-deps
